
# --------------------------------------------------------------------------------------------------------------
# 获取系统状态
# --------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------
# 请求头
CommonRequest header

# ---------------------------------------------------- req
---
# ---------------------------------------------------

# ---------------------------------------------------- resp
# 响应头
CommonResponse header

# -----------------------------------------------------
# 当前系统状态名
string cur_state

# ----------------------------------------------------
# 系统当前情况
SystemStatus curr_status