
# --------------------------------------------------------------------------------------------------------------
# 设置系统状态
# --------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------
# 请求头
CommonRequest header

#----------------------------------------------------
# 请求切换的系统状态
string state

# ---------------------------------------------------- req
---
# ---------------------------------------------------

# ---------------------------------------------------- resp
# 响应头
CommonResponse header
